# Generated by Django 5.0.6 on 2024-07-15 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('brgy_captain', models.CharField(blank=True, max_length=80, null=True)),
                ('population', models.IntegerField(blank=True, default=0, null=True)),
                ('lumon', models.IntegerField(blank=True, default=0, null=True)),
                ('catholic', models.IntegerField(blank=True, default=0, null=True)),
                ('not_baptized', models.IntegerField(blank=True, default=0, null=True)),
                ('not_confirmed', models.IntegerField(blank=True, default=0, null=True)),
                ('not_married', models.IntegerField(blank=True, default=0, null=True)),
                ('professionals', models.IntegerField(blank=True, default=0, null=True)),
                ('stop_highschool', models.IntegerField(blank=True, default=0, null=True)),
                ('stop_college', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'barangay',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('members', models.IntegerField(blank=True, null=True)),
                ('catholic', models.IntegerField(blank=True, null=True)),
                ('mass_attendance', models.CharField(blank=True, max_length=30, null=True)),
                ('not_baptized', models.IntegerField(blank=True, null=True)),
                ('not_confirmed', models.IntegerField(blank=True, null=True)),
                ('not_married', models.IntegerField(blank=True, null=True)),
                ('professionals', models.IntegerField(blank=True, null=True)),
                ('stop_highschool', models.IntegerField(blank=True, null=True)),
                ('stop_college', models.IntegerField(blank=True, null=True)),
                ('living_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('has_lumon', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.admin')),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='households.barangay')),
                ('encoder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'db_table': 'households',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lumon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
                ('members', models.IntegerField(blank=True, null=True)),
                ('catholic', models.IntegerField(blank=True, null=True)),
                ('mass_attendance', models.CharField(blank=True, max_length=30, null=True)),
                ('not_baptized', models.IntegerField(blank=True, null=True)),
                ('not_confirmed', models.IntegerField(blank=True, null=True)),
                ('not_married', models.IntegerField(blank=True, null=True)),
                ('professionals', models.IntegerField(blank=True, null=True)),
                ('stop_highschool', models.IntegerField(blank=True, null=True)),
                ('stop_college', models.IntegerField(blank=True, null=True)),
                ('living_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.admin')),
                ('encoder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
                ('households', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='households.households')),
            ],
            options={
                'db_table': 'lumon',
                'managed': True,
            },
        ),
    ]
